[WIP] Linker error while Refactor ownership and types for targetting
Linker error:
[ 61%] Linking CXX executable freeorion
CMakeFiles/freeorion.dir/combat/CombatSystem.cpp.o: In function `(anonymous namespace)::ShipWeaponsStrengths(std::shared_ptr<Ship const>)':
CombatSystem.cpp:(.text+0x7223): undefined reference to `Targetting::WrapCondition(Condition::ConditionBase const*&&)

* TriggerConditions take shared ownership of conditions, (share_ptr)
  because we need some pointer/ref type for the vector and it prepares for usage in ShipPart or Design
* PartAttackInfo does not take ownership (TriggerConditions&) because it only lasts while processing the combat