Remove transitive dependency in Techs
We have two tech paths to LRN_GATEWAY_VOID from LRN_NDIM_SUBSPACE

1) LRN_GATEWAY_VOID -> LRN_NDIM_SUBSPACE
2) LRN_GATEWAY_VOID -> CON_STARGATE -> LRN_SPATIAL_DISTORT_GEN -> LRN_SPATIAL_DISTORT_GEN -> LRN_NDIM_SUBSPACE

We would like to break one of the paths to simplify code.

Log error suggests breaking somewhere in the second path (it's a bit confusing and takes me some time to build a real picture in my head).

```
tech.cpp:529 : ERROR: Redundant tech dependency found (A <-- B means A is a prerequisite of B):
LRN_SPATIAL_DISTORT_GEN <-- CON_STARGATE,
CON_STARGATE <-- LRN_GATEWAY_VOID,
LRN_SPATIAL_DISTORT_GEN <-- LRN_GATEWAY_VOID;
remove the LRN_SPATIAL_DISTORT_GEN <-- LRN_GATEWAY_VOID dependency.
```

Im my opinion we should break the first path, since this will not affect research process.