Reverted commit#7234, as these changes caused the dynamic linker on OSX to throw the following error during universe generation: "dyld: Symbol not found: __Z17GetUniverseObjecti" (referenced from freeorioncommon.dylib).
svn path=/trunk/FreeOrion/; revision=7242